### ISSUE TITLE
Clarification on Certificate Signing

### ISSUE THREAD

**Issue by victorwiebe** [ConsenSys/ERC1400#43]
Hi there Consensys team,

After having read the source code for this project I think I understand the basic use. What I didn’t follow however is Certificate Signing. Reading source code and the description, it is more than clear for me that this feature Can be toggled on or off, that there is a list of certificate signers, etc. I checked the tests and found the strings that denote signed certificates.

But I got a bit lost with the part about creating the certificate string, and the certificate controller mock. Is the intention for the developer to fork the code and replace with their own certificate controller solidity code? Or do you have a seperate sol file? 

Is there perhaps an example of how someone (holding the wallet corresponding to the certificate issuer) Can use web3 to sign some method and parameter data to generate the certificate data String?

All the best
Victor

**Comment by gauthierpetetin** [comment]
Hello Victor,

Yes exactly, your understanding is correct:
 - The certificate controller imported on l.13 of this [file](https://github.com/ConsenSys/ERC1400/blob/master/contracts/token/ERC1400Raw/ERC1400Raw.sol) on the master branch is a mock
 - The certificate controllers we really use on the Codefi Assets platform are those on the branches [feat/v2_nonce](https://github.com/ConsenSys/ERC1400/blob/feat/v2_nonce/contracts/token/ERC1400Raw/ERC1400Raw.sol) and [feat/v2_salt](https://github.com/ConsenSys/ERC1400/blob/feat/v2_salt/contracts/token/ERC1400Raw/ERC1400Raw.sol). The way those CertificateControllers work is, they perform an [ecRecover](https://github.com/protofire/zeppelin-solidity/blob/master/contracts/ECRecovery.sol) operation over a piece of data signed off-chain by a certificate signer (and passed to the ERC1400 through the data/operatorData parameters of the issuance/transfer/redemption functions). Those CertificateControllers contracts are currently on private repos, but we'll add them to this public repo very soon, as well as other contracts of our library (delivery-vs-payment, fund issuance).

This being said, here are the ways we recommend using this standard now:
 - **No verification**: toggle off the certificate verification feature
 - **Whitelist verification**: , add the [token extension](https://github.com/ConsenSys/ERC1400/blob/master/contracts/tokenExtension/ERC1400TokensValidator.sol), and toggle on the whitelist feature
 - **Certificate/Custom verification**: fork the repo to add your own certificate controller, and toggle on the certificate feature. This option is probably the most complex as it requires an off-chain module to generate certificates at every transfer.

I hope this helps. Best

**Comment by victorwiebe** [comment]
Hello, yes this helps thank you for taking the time to respond. 

One more question, I am trying to deploy ERC1400ERC20.sol . I have flattened the solidity files and threw it into remix to do some initial testing. It seems the contract size is very large. Were you guys able to deploy this flattened? Or did you have to split it up into several deployed contracts? Any tips would be very helpful thanks

**Comment by gauthierpetetin** [comment]
There are a high number of features we would like to add in the ERC1400 smart contract.
The problem his, we’re limited by the maximum size the deployment transaction can support.
2 approaches can be considered:
 - Either split the ERC1400 into multiple smart contracts, in order to deploy it in multiple times
 - Or reduce the number of features in the smart contract

We propose the following compromise:
 - ERC1400 shall be deployable in one single transaction as much as possible. That’s why we propose a single smart contract containing all the “core features”
 - In specific use cases, where additional features are required (Ex: whitelist, blacklist, dividend distribution, etc.), a “token extension” smart contract can be deployed. The extension is then linked to the ERC1400 by calling the “setHookContract” function.

Here are some answers:
1) Tokens validator is an optional extension to ERC1400 which is triggered every time a transfer is executed. The implementation proposed in this repo contains whitelist and blacklist features but it could contain other features depending on your needs. The advantage of this module is that it can be updated whenever you want and replaced by another extension smart contract. It can indeed be used for KYC validations, by using the whitelist feature.

2) I would recommend you to use ERC1400 as it is without modifying it, and build a custom extension to add your custom logic (limiting the max % of total partition tokens a certain tokenholder can hold).

2) “canTransfer” has also been removed from the ERC1400 because it takes to much size. But it can be added as an extension by deploying the “ERC1400TokensChecker” extension.

3) We built a fund issuance smart contract, to achieve subscriptions and order management. It is structured in 4 periods: subscription, valuation (after cut-off), payment, settlement. We’ll try to open-source it asap.

**Comment by victorwiebe** [comment]
> Either split the ERC1400 into multiple smart contracts, in order to deploy it in multiple times

This would probably look like splitting the contract up into libraries
   deployer.deploy(Library);
    deployer.link(Library, MainContract);
To do something like this, where would one start?

- We have been able to flatten and deploy ERC1400ERC20, however indeed it seems to be at the limit of contract size.

- We have been able to create a factory to deploy an ERC1400 and set its ownership and sethook in a single call. However ERC1400ERC20 is simply too big even removing some functions.



1. Understood

2. Can I add many different hook token extensions? Or must be all in one contract?

3. Is ERC1400TokensChecker added in the same way as ERC1400TokensValidator? i.e. "setHookContract"?

4. Would be very useful to have these other contracts, let me know if there is some timeline that the open source community can expect those.

All the best and stay safe during these times.

**Comment by gauthierpetetin** [comment]
We've designed this contract, with the objective to cover all uses cases we were likely to encounter in financial asset tokenization. This is why it provides different ways to control transfers:
 - Level1: possibility to blacklist/whitelist
 - Level2: possibility to forceTransfer
 - Level3: possibility to perform certificate verification for every transfer (most granular check)
And at the same time we wanted the contract to be deployable in a single transaction, which lead us to this large contract.
A first step to reduce its size is to remove the CertificateController if you don't use it and rely on "ERC1400TokensValidator" extension to control the transfers.

Otherwise, we have a project to develop a new "minimal" generic implementation of the standard to push it [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts). Part of this project will also be to get it listed as an ERC on [EIP](https://eips.ethereum.org/).
This "minimal" generic implementation of the standard will be more flexible and easier to include in a factory like you mention.

1. NA
2. You can add one single "ERC1400TokensValidator" token extension. But if you need more, you can create your single extension as a proxy to multiple other extensions.
3. Yes "ERC1400TokensChecker" can be added exactly in the same way as "ERC1400TokensValidator", thanks to the "setHookContract". [ERC1820](https://github.com/0xjac/ERC1820/blob/master/contracts/ERC1820Registry.sol) in an on-chain registry that stores the mapping between your main ERC1400 contract's address and the addresses of it's extensions (ERC1400TokensValidator, ERC1400TokensChecker, etc.). Furthermore, every time you register an extension contract in ERC1820 registry, it verifies your contract implements the correct interface, in order to avoid errors when setting your extensions.
4. Sure we'll open-source all of them soon:

 - The CertificateControllers (nonce-based and salt-based) contracts will be merged this week - Actually, It's already on a [branch](https://github.com/ConsenSys/ERC1400/tree/feature/merge-certificate-controller/contracts/CertificateController) if you want to have a look
 - The BalanceReader contract will be merged this week - it's also on a [branch](https://github.com/ConsenSys/ERC1400/blob/feature/balance-reader/contracts/tools/BalanceReader.sol)
 - The Delivery-vs-payment will be merged this week
 - The Fund issuance contract by end of April
Nice for multiple partition issuance! (fyi we've included it in fund issuance contract)
